# # Nome da Actions:
# name: Snake Game

# # Controlador do tempo que sera feito a atualização dos arquivos.
# on:
#   schedule:
#       # Será atualizado a cada 5 horas.
#     - cron: "0 */5 * * *"

# # Permite executar na na lista de Actions (utilizado para testes de build).
#   workflow_dispatch:

# # Regras
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
#       - name: generate github-contribution-grid-snake.svg
#         uses: Platane/snk/svg-only@v3
#         with:
#           github_user_name: ${{ github.repository_owner }}
#           outputs: |
#             dist/github-contribution-grid-snake.svg
#             dist/github-contribution-grid-snake-dark.svg?palette=github-dark

#     # Checks repo under $GITHUB_WORKSHOP, so your job can access it
#       - uses: actions/checkout@v2

#     # Repositorio que será utilizado para gerar os arquivos.
#       - uses: Platane/snk@master
#         id: snake-gif
#         with:
#           github_user_name: Albertinesilva
#           gif_out_path: dist/github-contribution-grid-snake-dark.svg?palette=github-dar
#           svg_out_path: dist/github-contribution-grid-snake-dark.svg?palette=github-dar

#       - run: git status

#       # Para as atualizações.
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: master
#           force: true

#       - uses: crazy-max/ghaction-github-pages@v2.1.3
#         with:
#           # the output branch we mentioned above
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Generate Snake and Pacman Graphs

on:
  schedule:
    - cron: "0 */6 * * *" # Executa a cada 6 horas
  workflow_dispatch: # Permite executar manualmente se necessário

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      # Passo 1: Verificar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Gerar o gráfico Snake
      - name: Generate snake graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Passo 3: Gerar o gráfico Pacman
      - name: Generate pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman.svg
            dist/pacman-dark.svg?palette=github-dark

      # Passo 4: Push para a branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
