# on:
#   schedule: # execute every 12 hours
#     - cron: "* */12 * * *"

#   workflow_dispatch:

#   push:
#     branches:
#     - master

# jobs:
#   generate:
#     permissions:
#       contents: write
#     runs-on: ubuntu-latest
#     timeout-minutes: 5

#     steps:
#       - name: generate snake.svg
#         uses: Platane/snk/svg-only@v3
#         with:
#           github_user_name: ${{ github.repository_owner }}
#           outputs: dist/snake.svg?palette=github-dark

#       - name: push snake.svg to the output branch
#         uses: crazy-max/ghaction-github-pages@v3.1.0
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Generate Snake and Pacman Graphs

on:
  schedule:
    - cron: "0 */6 * * *"  # Execute a cada 6 horas
  workflow_dispatch:  # Execute manualmente, se necessário

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Generate pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman.svg
            dist/pacman-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

