name: Generate Snake and Pacman Graphs

on:
  schedule:
    - cron: "0 */6 * * *" # Executa a cada 6 horas
  workflow_dispatch: # Permite executar manualmente se necess치rio

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      # Passo 1: Verificar o reposit칩rio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Gerar o gr치fico Snake
      - name: Generate snake graph
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Passo 3: Gerar o gr치fico Pacman
      - name: Generate pacman graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman.svg
            dist/pacman-dark.svg?palette=github-dark

      # Passo 4: Push para a branch 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
